# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: THL UI Components
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  React components to help building application websites.
baseurl: http://thl-dev.github.io/thl-ui-components/
github_username:  THL-DEV

# Build settings
markdown: kramdown
